all:
	cd qed && make $@
	cd rpa && make $@
	cd all-order && make $@

clean:
	cd qed && make $@
	cd rpa && make $@
	cd all-order && make $@

install:
	cd qed && make $@
	cd rpa && make $@
	cd all-order && make $@

rpa:
	cd rpa && make install

qed:
	cd qed && make install

all-order:
	cd all-order && make install

.PHONY : all clean install rpa qed all-order